### ISSUE TITLE
crash: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by DiegoRRR** [ks32/CrosswalkNative#2]
Once on the tablet it crashes.

From logcat :

12-02 03:29:17.091 16579-16594/ks32.crosswalk_native D/XWalkLib: XWalk core version matched
12-02 03:29:17.101 16579-16594/ks32.crosswalk_native D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
12-02 03:29:17.101 16579-16594/ks32.crosswalk_native W/dalvikvm: VFY: unable to resolve static field 585 (SUPPORTED_ABIS) in Landroid/os/Build;
12-02 03:29:17.101 16579-16594/ks32.crosswalk_native D/dalvikvm: VFY: replacing opcode 0x62 at 0x0004
12-02 03:29:17.111 16579-16594/ks32.crosswalk_native W/dalvikvm: Exception Ljava/lang/RuntimeException; thrown while initializing Lorg/xwalk/core/internal/XWalkViewDelegate;
12-02 03:29:17.111 16579-16594/ks32.crosswalk_native D/dalvikvm: Method.invoke() on bad class Lorg/xwalk/core/internal/XWalkViewDelegate; failed
12-02 03:29:17.111 16579-16594/ks32.crosswalk_native W/dalvikvm: threadid=12: thread exiting with uncaught exception (group=0x4184eba8)
12-02 03:29:17.121 16579-16594/ks32.crosswalk_native E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: ks32.crosswalk_native, PID: 16579
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ExceptionInInitializerError
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61)
        at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349)
        at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248)
        at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162)
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335)
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.lang.RuntimeException: Invalid reflection
        at org.xwalk.core.internal.XWalkViewDelegate.<clinit>(XWalkViewDelegate.java:71)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61) 
        at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349) 
        at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248) 
        at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.lang.NoSuchMethodException: getAssignedPackageIdentifiers []
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getMethod(Class.java:857)
        at org.xwalk.core.internal.XWalkViewDelegate.<clinit>(XWalkViewDelegate.java:69)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61) 
        at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349) 
        at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248) 
        at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
12-02 03:29:17.141 493-768/system_process W/ActivityManager:   Force finishing activity ks32.crosswalk_native/.MainActivity
12-02 03:29:17.151 16579-16579/ks32.crosswalk_native D/OpenGLRenderer: Enabling debug mode 0

The tablet runs Android 4.4 .

**Comment by DiegoRRR** [comment]
It crashes on my other tablet too, the error is different though.
This tablet runs Android 4.4 too but with an Intel Atom Z3735 SOC. (The other one has an ARM RK3188 SOC ) 

12-02 17:14:57.209 2711-2726/ks32.crosswalk_native D/XWalkLib: XWalk core version matched
12-02 17:14:57.209 2711-2726/ks32.crosswalk_native D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Build;.SUPPORTED_ABIS
12-02 17:14:57.209 2711-2726/ks32.crosswalk_native W/dalvikvm: VFY: unable to resolve static field 585 (SUPPORTED_ABIS) in Landroid/os/Build;
12-02 17:14:57.209 2711-2726/ks32.crosswalk_native D/dalvikvm: VFY: replacing opcode 0x62 at 0x0004
12-02 17:14:57.209 2711-2726/ks32.crosswalk_native W/dalvikvm: Exception Ljava/lang/RuntimeException; thrown while initializing Lorg/xwalk/core/internal/XWalkViewDelegate;
12-02 17:14:57.209 2711-2726/ks32.crosswalk_native D/dalvikvm: Method.invoke() on bad class Lorg/xwalk/core/internal/XWalkViewDelegate; failed
12-02 17:14:57.219 2711-2726/ks32.crosswalk_native W/dalvikvm: threadid=12: thread exiting with uncaught exception (group=0x4c850160)
12-02 17:14:57.219 2711-2726/ks32.crosswalk_native E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: ks32.crosswalk_native, PID: 2711
    java.lang.RuntimeException: An error occured while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:300)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.ExceptionInInitializerError
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61)
        at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349)
        at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248)
        at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162)
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335)
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.lang.RuntimeException: Invalid reflection
        at org.xwalk.core.internal.XWalkViewDelegate.<clinit>(XWalkViewDelegate.java:71)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61) 
        at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349) 
        at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248) 
        at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
     Caused by: java.lang.NoSuchMethodException: getAssignedPackageIdentifiers []
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getMethod(Class.java:857)
        at org.xwalk.core.internal.XWalkViewDelegate.<clinit>(XWalkViewDelegate.java:69)
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:61) 
        at org.xwalk.core.XWalkCoreWrapper.checkCoreArchitecture(XWalkCoreWrapper.java:349) 
        at org.xwalk.core.XWalkCoreWrapper.findEmbeddedCore(XWalkCoreWrapper.java:248) 
        at org.xwalk.core.XWalkCoreWrapper.attachXWalkCore(XWalkCoreWrapper.java:162) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:335) 
        at org.xwalk.core.XWalkLibraryLoader$ActivateTask.doInBackground(XWalkLibraryLoader.java:317) 
        at android.os.AsyncTask$2.call(AsyncTask.java:288) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841) 
12-02 17:14:57.219 563-2050/? W/ActivityManager:   Force finishing activity ks32.crosswalk_native/.MainActivity

**Comment by ks32** [comment]
I myself using older crosswalk for api =<21 due to crashes. Use crosswalk 54 for new api only.

**Comment by DiegoRRR** [comment]
Thanks for your reply.
What a shame, I stopped using the old Crosswalk because it had too serious bugs in both webaudio and html5audio, and my two testing devices have Android 4.4.
I see some people are setting up a funding and you will work on it. Is there any chance a future version will be compatible again with Android older than 5 ? I think Crosswalk is especially useful for supporting older Android versions because their webview can't be used for it is obsolete and can't be updated.

**Comment by DiegoRRR** [comment]
Are you still working on it ? Anything new ?

**Comment by ks32** [comment]
by next month I will start on chrome 64.

Pakistan Data Management Services
p: +92 21 3455 9003
w: www.pakdata.com
<https://facebook.com/pakdata>   <https://twitter.com/hashtag/Pakdata>
<https://www.instagram.com/pakdataapps/>
