### ISSUE TITLE
NoClassDefFoundError: org.chromium.base.ObserverList

### ISSUE THREAD

**Issue by deng81416754** [ks32/CrosswalkNative#37]
Hello author~
After modifying the minimum version to 19, the program crashes, can it only support 22 at the minimum?

ks32.crosswalk_native E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ks32.crosswalk_native, PID: 3005
    java.lang.NoClassDefFoundError: org.chromium.base.ObserverList
        at org.chromium.base.ApplicationStatus.<clinit>(ApplicationStatus.java:97)
        at ks32.crosswalk_native.App.onCreate(App.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by ks32** [comment]
it should support SDK 21 and later. For SDK 19 you will need to use crosswalk-23.
