### ISSUE TITLE
The app crash onCreate

### ISSUE THREAD

**Issue by maxiannunziata** [ks32/CrosswalkNative#42]
Logcat:

`2022-07-04 20:06:28.548 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
2022-07-04 20:06:28.687 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden field Landroid/view/WindowInsets;->CONSUMED:Landroid/view/WindowInsets; (light greylist, reflection)
2022-07-04 20:06:28.716 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
2022-07-04 20:06:28.839 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
2022-07-04 20:06:28.842 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
2022-07-04 20:06:28.932 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (light greylist, reflection)
2022-07-04 20:06:28.932 30393-30393/ks32.crosswalk_native W/rosswalk_nativ: Accessing hidden method Landroid/app/ActivityThread;->getProcessName()Ljava/lang/String; (light greylist, reflection)
2022-07-04 20:06:28.951 30393-30393/ks32.crosswalk_native D/AndroidRuntime: Shutting down VM
2022-07-04 20:06:28.957 30393-30393/ks32.crosswalk_native E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ks32.crosswalk_native, PID: 30393
    java.lang.AssertionError
        at org.chromium.base.ApplicationStatus.initialize(ApplicationStatus.java:232)
        at org.xwalk.core.XWalkInitializer.<init>(XWalkInitializer.java:181)
        at ks32.crosswalk_native.MainActivity.onCreate(MainActivity.java:28)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2022-07-04 20:06:28.981 30393-30393/ks32.crosswalk_native I/Process: Sending signal. PID: 30393 SIG: 9`

Tested on:

Operating System: Android TV 9

**Comment by berserkore** [comment]
Hi @ks32, Do you have any clue about this issue? seems to be happening over every devices from master repo
