### ISSUE TITLE
org.chromium.base.ApplicationStatus.initialize Issue

### ISSUE THREAD

**Issue by ShadowViolet** [ks32/CrosswalkNative#45]
FATAL EXCEPTION: main
                                                                                                    Process: ks32.crosswalk_native, PID: 14159
                                                                                                    java.lang.AssertionError
                                                                                                    	at org.chromium.base.ApplicationStatus.initialize(ApplicationStatus.java:232)
                                                                                                    	at org.xwalk.core.XWalkInitializer.<init>(XWalkInitializer.java:181)
                                                                                                    	at ks32.crosswalk_native.MainActivity.onCreate(MainActivity.java:28)

**Comment by ShadowViolet** [comment]
I downloaded this project Nothing was modified Compiled successfully but ran error, the program crashed directly

**Comment by ks32** [comment]
I am unable to push fix due to:
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to push some refs to 'https://github.com/ks32/CrosswalkNative.git'

**Comment by hthetiot** [comment]
@ks32 in my humble advice you could ask for donation and apply to github sponsor to solve the quota issue. Alternatively you may store file on AWS S3.
