### ISSUE TITLE
gclient sync ERRO and  gn args out/Default ERRO

### ISSUE THREAD

**Issue by HYRobin** [ks32/CrosswalkNative#8]
My steps as follows:

step 1:
export XWALK_OS_ANDROID=1
step 2:
gclient config --name src/xwalk https://github.com/ks32/crosswalk.git@origin/ks_chromium_58
step 3:
echo "target_os = [ 'android' ]" >> ./.gclient
step 4:
gclient sync
	ERRO:
	{
		 Traceback (most recent call last):
			  File "src/xwalk/tools/fetch_deps.py", line 83, in <module>
			    sys.exit(main())
			  File "src/xwalk/tools/fetch_deps.py", line 78, in main
			    deps_fetcher.DoGclientSyncForChromium()
			  File "src/xwalk/tools/fetch_deps.py", line 53, in DoGclientSyncForChromium
			    gclient_utils.CheckCallAndFilterAndHeader(gclient_cmd,
			AttributeError: 'module' object has no attribute 'CheckCallAndFilterAndHeader'
			Error: Command 'vpython src/xwalk/tools/fetch_deps.py -v' returned non-zero exit
	}

instead of  gclient sync --verbose --reset --force --with_branch_heads --delete_unversioned_trees --gclientfile=.gclient-xwalk  is successful.

step 5:
cd src
./build/install-build-deps.sh
./build/install-build-deps-android.sh

step 6:
gn args out/Default
{
	import("//xwalk/build/android.gni")
	is_debug = false
	target_os = "android"
	target_cpu = "arm"
}

got erro:

{
	Waiting for editor on "/home/crosswalk/src/out/Default/args.gn"...
	Generating files...
	ERROR at //media/BUILD.gn:35:3: Assertion failed.
	  assert(
	  ^-----
	proprietary codecs and ffmpeg_branding set to Chromium are incompatible
	See //media/BUILD.gn:36:7:
	      ffmpeg_branding != "Chromium",
	      ^----------------------------
	This is where it was set.
	See //BUILD.gn:297:7: which caused the file to be included.
      "//media:media_unittests",
      ^------------------------
}

please help me ,how to solve this problem. is there any step  i omitted ?

**Comment by HYRobin** [comment]
i copy m2repository from other project and gn  args out/default can successfully
